resolver: lts-15.6

allow-newer: true

packages:
- 'simple-app'
- 'simple-lib'

apply-ghc-options: everything
ghc-options:
  "$everything": -split-sections -O0

# use custom ext-stg whole program compiler GHC
compiler:     ghc-8.11.0.20200527
ghc-variant:  ext-stg-whole-program-compiler

setup-info-locations: []
setup-info:
  ghc:
    linux64-custom-ext-stg-whole-program-compiler:
      8.11.0.20200527:
        url: "https://github.com/grin-compiler/ghc-wpc/releases/download/ghc-8.11.0.20200527-wpc/ghc-8.11.0.20200527.tar.xz"
